renovate:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: docker.io/renovate/renovate:37.107.0@sha256:9b91d04e144f410c261aec5c9fd19ebc84f756efce35310fe7a43b0026add46f
  variables:
    LOG_LEVEL: debug
    RENOVATE_ENDPOINT: ${CI_API_V4_URL}
    RENOVATE_GIT_AUTHOR: "${GITLAB_USER_NAME} <${GITLAB_USER_EMAIL}>"
    RENOVATE_PLATFORM: gitlab
    RENOVATE_REPOSITORIES: '["${CI_PROJECT_PATH}"]'
    RENOVATE_TOKEN: ${RENOVATE_TOKEN}
    RENOVATE_X_PLATFORM_VERSION: ${CI_SERVER_VERSION}
  before_script:
    - test -n "${RENOVATE_ENDPOINT:?}"
    - test -n "${GITLAB_USER_NAME:?}"
    - test -n "${GITLAB_USER_EMAIL:?}"
    - test -n "${RENOVATE_GIT_AUTHOR:?}"
    - test "${RENOVATE_GIT_AUTHOR:?}" != ' <>'
    - test -n "${RENOVATE_PLATFORM:?}"
    - test -n "${CI_PROJECT_PATH:?}"
    - test -n "${RENOVATE_REPOSITORIES:?}"
    - test "${RENOVATE_REPOSITORIES:?}" != '[""]'
    - test -n "${RENOVATE_TOKEN:?}"
    - test "${RENOVATE_TOKEN:?}" != '${RENOVATE_TOKEN}'
    - test -n "${CI_SERVER_VERSION:?}"
    - test -n "${RENOVATE_X_PLATFORM_VERSION:?}"
  script:
    - renovate

alpine:
  stage: test
  image: busybox:1.36.0-musl
  script:
    - echo hello

busybox:
  stage: test
  image: alpine:3.18.4
  script:
    - echo hello
